// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: main.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Handshake_Error int32

const (
	Handshake_UNKNOWN Handshake_Error = 0
	Handshake_OK      Handshake_Error = 1
	Handshake_STARTED Handshake_Error = 2
)

// Enum value maps for Handshake_Error.
var (
	Handshake_Error_name = map[int32]string{
		0: "UNKNOWN",
		1: "OK",
		2: "STARTED",
	}
	Handshake_Error_value = map[string]int32{
		"UNKNOWN": 0,
		"OK":      1,
		"STARTED": 2,
	}
)

func (x Handshake_Error) Enum() *Handshake_Error {
	p := new(Handshake_Error)
	*p = x
	return p
}

func (x Handshake_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Handshake_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_main_proto_enumTypes[0].Descriptor()
}

func (Handshake_Error) Type() protoreflect.EnumType {
	return &file_main_proto_enumTypes[0]
}

func (x Handshake_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Handshake_Error.Descriptor instead.
func (Handshake_Error) EnumDescriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{0, 0}
}

type Error_EType int32

const (
	Error_UNKNOWN    Error_EType = 0
	Error_DISCONNECT Error_EType = 1
	Error_BADNAME    Error_EType = 2
)

// Enum value maps for Error_EType.
var (
	Error_EType_name = map[int32]string{
		0: "UNKNOWN",
		1: "DISCONNECT",
		2: "BADNAME",
	}
	Error_EType_value = map[string]int32{
		"UNKNOWN":    0,
		"DISCONNECT": 1,
		"BADNAME":    2,
	}
)

func (x Error_EType) Enum() *Error_EType {
	p := new(Error_EType)
	*p = x
	return p
}

func (x Error_EType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error_EType) Descriptor() protoreflect.EnumDescriptor {
	return file_main_proto_enumTypes[1].Descriptor()
}

func (Error_EType) Type() protoreflect.EnumType {
	return &file_main_proto_enumTypes[1]
}

func (x Error_EType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error_EType.Descriptor instead.
func (Error_EType) EnumDescriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{5, 0}
}

type Alert_Msg int32

const (
	Alert_UNKNOWN         Alert_Msg = 0
	Alert_NEEDMOREPLAYERS Alert_Msg = 1
)

// Enum value maps for Alert_Msg.
var (
	Alert_Msg_name = map[int32]string{
		0: "UNKNOWN",
		1: "NEEDMOREPLAYERS",
	}
	Alert_Msg_value = map[string]int32{
		"UNKNOWN":         0,
		"NEEDMOREPLAYERS": 1,
	}
)

func (x Alert_Msg) Enum() *Alert_Msg {
	p := new(Alert_Msg)
	*p = x
	return p
}

func (x Alert_Msg) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Alert_Msg) Descriptor() protoreflect.EnumDescriptor {
	return file_main_proto_enumTypes[2].Descriptor()
}

func (Alert_Msg) Type() protoreflect.EnumType {
	return &file_main_proto_enumTypes[2]
}

func (x Alert_Msg) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Alert_Msg.Descriptor instead.
func (Alert_Msg) EnumDescriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{6, 0}
}

type SetCharacter_Character int32

const (
	SetCharacter_NONE     SetCharacter_Character = 0
	SetCharacter_CITIZEN  SetCharacter_Character = 1
	SetCharacter_WEREWOLF SetCharacter_Character = 2
	SetCharacter_HEALER   SetCharacter_Character = 3
	SetCharacter_PROPHET  SetCharacter_Character = 4
	SetCharacter_HUNTER   SetCharacter_Character = 5
)

// Enum value maps for SetCharacter_Character.
var (
	SetCharacter_Character_name = map[int32]string{
		0: "NONE",
		1: "CITIZEN",
		2: "WEREWOLF",
		3: "HEALER",
		4: "PROPHET",
		5: "HUNTER",
	}
	SetCharacter_Character_value = map[string]int32{
		"NONE":     0,
		"CITIZEN":  1,
		"WEREWOLF": 2,
		"HEALER":   3,
		"PROPHET":  4,
		"HUNTER":   5,
	}
)

func (x SetCharacter_Character) Enum() *SetCharacter_Character {
	p := new(SetCharacter_Character)
	*p = x
	return p
}

func (x SetCharacter_Character) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetCharacter_Character) Descriptor() protoreflect.EnumDescriptor {
	return file_main_proto_enumTypes[3].Descriptor()
}

func (SetCharacter_Character) Type() protoreflect.EnumType {
	return &file_main_proto_enumTypes[3]
}

func (x SetCharacter_Character) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetCharacter_Character.Descriptor instead.
func (SetCharacter_Character) EnumDescriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{7, 0}
}

type Handshake struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err Handshake_Error `protobuf:"varint,1,opt,name=err,proto3,enum=murdermystery.Handshake_Error" json:"err,omitempty"`
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{0}
}

func (x *Handshake) GetErr() Handshake_Error {
	if x != nil {
		return x.Err
	}
	return Handshake_UNKNOWN
}

type Host struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsHost bool `protobuf:"varint,1,opt,name=isHost,proto3" json:"isHost,omitempty"`
}

func (x *Host) Reset() {
	*x = Host{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{1}
}

func (x *Host) GetIsHost() bool {
	if x != nil {
		return x.IsHost
	}
	return false
}

type SetName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SetName) Reset() {
	*x = SetName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetName) ProtoMessage() {}

func (x *SetName) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetName.ProtoReflect.Descriptor instead.
func (*SetName) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{2}
}

func (x *SetName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StartGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartGame) Reset() {
	*x = StartGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGame) ProtoMessage() {}

func (x *StartGame) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGame.ProtoReflect.Descriptor instead.
func (*StartGame) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{3}
}

type Players struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players []*Players_Player `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	HostId  int32             `protobuf:"varint,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
}

func (x *Players) Reset() {
	*x = Players{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Players) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Players) ProtoMessage() {}

func (x *Players) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Players.ProtoReflect.Descriptor instead.
func (*Players) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{4}
}

func (x *Players) GetPlayers() []*Players_Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *Players) GetHostId() int32 {
	if x != nil {
		return x.HostId
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg Error_EType `protobuf:"varint,1,opt,name=msg,proto3,enum=murdermystery.Error_EType" json:"msg,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{5}
}

func (x *Error) GetMsg() Error_EType {
	if x != nil {
		return x.Msg
	}
	return Error_UNKNOWN
}

type Alert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg Alert_Msg `protobuf:"varint,1,opt,name=msg,proto3,enum=murdermystery.Alert_Msg" json:"msg,omitempty"`
}

func (x *Alert) Reset() {
	*x = Alert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{6}
}

func (x *Alert) GetMsg() Alert_Msg {
	if x != nil {
		return x.Msg
	}
	return Alert_UNKNOWN
}

type SetCharacter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Character SetCharacter_Character `protobuf:"varint,1,opt,name=character,proto3,enum=murdermystery.SetCharacter_Character" json:"character,omitempty"`
}

func (x *SetCharacter) Reset() {
	*x = SetCharacter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetCharacter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCharacter) ProtoMessage() {}

func (x *SetCharacter) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCharacter.ProtoReflect.Descriptor instead.
func (*SetCharacter) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{7}
}

func (x *SetCharacter) GetCharacter() SetCharacter_Character {
	if x != nil {
		return x.Character
	}
	return SetCharacter_NONE
}

type FellowWolves struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int32 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *FellowWolves) Reset() {
	*x = FellowWolves{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FellowWolves) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FellowWolves) ProtoMessage() {}

func (x *FellowWolves) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FellowWolves.ProtoReflect.Descriptor instead.
func (*FellowWolves) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{8}
}

func (x *FellowWolves) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type Players_Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   int32  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Players_Player) Reset() {
	*x = Players_Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Players_Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Players_Player) ProtoMessage() {}

func (x *Players_Player) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Players_Player.ProtoReflect.Descriptor instead.
func (*Players_Player) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Players_Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Players_Player) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_main_proto protoreflect.FileDescriptor

var file_main_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6d, 0x75,
	0x72, 0x64, 0x65, 0x72, 0x6d, 0x79, 0x73, 0x74, 0x65, 0x72, 0x79, 0x22, 0x68, 0x0a, 0x09, 0x48,
	0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x12, 0x30, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x6d, 0x75, 0x72, 0x64, 0x65, 0x72, 0x6d, 0x79,
	0x73, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x29, 0x0a, 0x05, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41, 0x52,
	0x54, 0x45, 0x44, 0x10, 0x02, 0x22, 0x1e, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x69, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69,
	0x73, 0x48, 0x6f, 0x73, 0x74, 0x22, 0x1d, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x0b, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d,
	0x65, 0x22, 0x89, 0x01, 0x0a, 0x07, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x37, 0x0a,
	0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x6d, 0x75, 0x72, 0x64, 0x65, 0x72, 0x6d, 0x79, 0x73, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x07, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x1a,
	0x2c, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x6a, 0x0a,
	0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2d, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6d, 0x75, 0x72, 0x64, 0x65, 0x72, 0x6d, 0x79, 0x73, 0x74,
	0x65, 0x72, 0x79, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x45, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x32, 0x0a, 0x06, 0x45, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a,
	0x44, 0x49, 0x53, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07,
	0x42, 0x41, 0x44, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x02, 0x22, 0x5c, 0x0a, 0x05, 0x41, 0x6c, 0x65,
	0x72, 0x74, 0x12, 0x2a, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x18, 0x2e, 0x6d, 0x75, 0x72, 0x64, 0x65, 0x72, 0x6d, 0x79, 0x73, 0x74, 0x65, 0x72, 0x79, 0x2e,
	0x41, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x27,
	0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x4e, 0x45, 0x45, 0x44, 0x4d, 0x4f, 0x52, 0x45, 0x50, 0x4c,
	0x41, 0x59, 0x45, 0x52, 0x53, 0x10, 0x01, 0x22, 0xaa, 0x01, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x12, 0x43, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x6d, 0x75,
	0x72, 0x64, 0x65, 0x72, 0x6d, 0x79, 0x73, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x53, 0x65, 0x74, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x52, 0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x22, 0x55, 0x0a,
	0x09, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f,
	0x4e, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x49, 0x54, 0x49, 0x5a, 0x45, 0x4e, 0x10,
	0x01, 0x12, 0x0c, 0x0a, 0x08, 0x57, 0x45, 0x52, 0x45, 0x57, 0x4f, 0x4c, 0x46, 0x10, 0x02, 0x12,
	0x0a, 0x0a, 0x06, 0x48, 0x45, 0x41, 0x4c, 0x45, 0x52, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x50,
	0x52, 0x4f, 0x50, 0x48, 0x45, 0x54, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x48, 0x55, 0x4e, 0x54,
	0x45, 0x52, 0x10, 0x05, 0x22, 0x20, 0x0a, 0x0c, 0x46, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x57, 0x6f,
	0x6c, 0x76, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x03, 0x69, 0x64, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_main_proto_rawDescOnce sync.Once
	file_main_proto_rawDescData = file_main_proto_rawDesc
)

func file_main_proto_rawDescGZIP() []byte {
	file_main_proto_rawDescOnce.Do(func() {
		file_main_proto_rawDescData = protoimpl.X.CompressGZIP(file_main_proto_rawDescData)
	})
	return file_main_proto_rawDescData
}

var file_main_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_main_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_main_proto_goTypes = []interface{}{
	(Handshake_Error)(0),        // 0: murdermystery.Handshake.Error
	(Error_EType)(0),            // 1: murdermystery.Error.E_type
	(Alert_Msg)(0),              // 2: murdermystery.Alert.Msg
	(SetCharacter_Character)(0), // 3: murdermystery.SetCharacter.Character
	(*Handshake)(nil),           // 4: murdermystery.Handshake
	(*Host)(nil),                // 5: murdermystery.Host
	(*SetName)(nil),             // 6: murdermystery.SetName
	(*StartGame)(nil),           // 7: murdermystery.StartGame
	(*Players)(nil),             // 8: murdermystery.Players
	(*Error)(nil),               // 9: murdermystery.Error
	(*Alert)(nil),               // 10: murdermystery.Alert
	(*SetCharacter)(nil),        // 11: murdermystery.SetCharacter
	(*FellowWolves)(nil),        // 12: murdermystery.FellowWolves
	(*Players_Player)(nil),      // 13: murdermystery.Players.Player
}
var file_main_proto_depIdxs = []int32{
	0,  // 0: murdermystery.Handshake.err:type_name -> murdermystery.Handshake.Error
	13, // 1: murdermystery.Players.players:type_name -> murdermystery.Players.Player
	1,  // 2: murdermystery.Error.msg:type_name -> murdermystery.Error.E_type
	2,  // 3: murdermystery.Alert.msg:type_name -> murdermystery.Alert.Msg
	3,  // 4: murdermystery.SetCharacter.character:type_name -> murdermystery.SetCharacter.Character
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_main_proto_init() }
func file_main_proto_init() {
	if File_main_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_main_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Handshake); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Host); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Players); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Alert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetCharacter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FellowWolves); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Players_Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_main_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_main_proto_goTypes,
		DependencyIndexes: file_main_proto_depIdxs,
		EnumInfos:         file_main_proto_enumTypes,
		MessageInfos:      file_main_proto_msgTypes,
	}.Build()
	File_main_proto = out.File
	file_main_proto_rawDesc = nil
	file_main_proto_goTypes = nil
	file_main_proto_depIdxs = nil
}
